name: "Build and release"

on:
  push:
    branches:
      - main
      - production

# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  packages: write # This is required to access container registry

jobs:
  build:
    name: Build production image
    runs-on: ubuntu-latest
    steps:
      - name: Clone whole repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pandev-srl/example-node-expressjs
          tags: |
            type=raw,value=v${{github.run_number}}
            type=sha,format=short,prefix=rev-
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            BUILD_VERSION=v${{ fromJSON(steps.meta.outputs.json).tags[0] }}
            BUILD_REF=v${{ fromJSON(steps.meta.outputs.json).tags[1] }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/cache.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cache
          path: /tmp/cache.tar

  # release-app1:
  #   name: Release production image for App1
  #   environment: App1-Production
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone whole repository
  #       uses: actions/checkout@v4
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: cache
  #         path: /tmp
  #     - name: Load image
  #       run: |
  #         docker load --input /tmp/cache.tar
  #         docker image ls -a
  #     - name: Setup docker meta
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: ghcr.io/pandev-srl/example-node-expressjs
  #         tags: |
  #           type=raw,value=v${{github.run_number}}
  #           type=sha,format=short,prefix=rev-
  #           type=raw,value=v${{github.run_number}}-app1-{{date 'x'}}
  #           type=sha,format=short,prefix=rev-,suffix=app1-{{date 'x'}}
  #     - name: Retag images for app1
  #       run: |
  #       docker pull
  #       # uses: docker/build-push-action@v6
  #       # with:
  #       #   context: .
  #       #   file: ./Dockerfile
  #       #   build-args: |
  #       #     BUILD_VERSION=v${{steps.meta.outputs.tags[0]}}
  #       #     BUILD_REF=v${{steps.meta.outputs.tags[1]}}
  #       #   push: true
  #       #   pull: true
  #       #   tags: ${{ steps.meta.outputs.tags }}
