name: "Build and release"

on:
  push:
    branches:
      - main
      - production

# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  packages: write # This is required to access container registry

jobs:
  build:
    name: Build production image
    runs-on: ubuntu-latest
    steps:
      - name: Clone whole repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pandev-srl/example-node-expressjs
          tags: |
            type=raw,value=v${{github.run_number}}
            type=sha,format=short,prefix=rev-
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  release-app1:
    name: Release production image for App1
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Setup docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pandev-srl/example-node-expressjs
          tags: |
            type=raw,value=v${{github.run_number}}
            type=raw,value=v${{github.run_number}}-{{date 'x'}}
            type=sha,format=short,prefix=rev-,suffix={{date 'x'}}
      - name: Retag images for
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
